# @package _global_
defaults:
  - _self_

# Test configuration
test:
  num_train: 64
  num_gen: 32
  train_engine_type: megatron  # fsdp, fsdp_hybrid, megatron
  
  # FSDP Hybrid configuration
  fsdp_hybrid:
    ddp_size: 2
    fsdp_size: 4
  
  # Megatron configuration
  megatron:
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 2
    virtual_pipeline_model_parallel_size: 1
    context_parallel_size: 1
  
  # Generation configuration
  gen:
    tensor_parallel_size: 2
    pipeline_parallel_size: 1

# Model configuration
model:
  path: ${oc.env:PSRL_WORKSPACE}/models/Qwen2.5-Math-7B

# Logging configuration
logging:
  path: ${oc.env:PSRL_WORKSPACE}/psrl/unit_tests/nixl/log
  level: INFO

# Network configuration
network:
  listen_ip: ${oc.env:LOCAL_IP}
  listen_port: 23459
  torch_port_train: 29502
  torch_port_gen: 29503
  backend: nccl

# NIXL configuration
nixl:
  server_mode: meta_server
  server_ip: ${network.listen_ip}
  server_port: ${network.listen_port}
  max_pinned_temp_memory_slots: 4
  enable_tms_for_temp_buffers: False # TMS (torch_memory_saver) is not used in unit tests

# PS configuration
ps:
  mode: nixl_cpu
  # num_ps will be calculated based on num_gen in the test
