import logging
import os
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Generic, TypeVar

import numpy as np
import ray
from omegaconf import DictConfig
from transformers import AutoTokenizer
from verl import DataProto

from psrl.environments.base import ConversationType, Environment

psrl_logger = logging.getLogger(__file__)
psrl_logger.setLevel(os.getenv("PSRL_LOGGING_LEVEL", "WARN"))


@dataclass
class Step:
    """
    Represents a single step in an agent's trajectory during rollout.

    This class encapsulates all information about one interaction step, including
    the conversation state, model response, action taken, and associated rewards.
    """

    # List of conversation messages at this step
    chat_completions: ConversationType = field(default_factory=list)

    # Environment observation received at this step
    observation: Any = None
    # Internal reasoning or thought process (if applicable)
    thought: str = ""
    # Action taken by the agent at this step
    action: Any = None
    # Raw text response generated by the model
    model_response: str = ""
    # Additional metadata or debug information
    info: dict = field(default_factory=dict)

    # Reward from tool execution (if applicable)
    tool_reward: float | None = None
    # Reward from model evaluation (if applicable)
    model_reward: float | None = None
    # Combined or final reward for this step
    reward: float | None = None
    # Whether this step terminates the episode
    done: bool = False

    def to_dict(self) -> dict:
        """Convert the step to a dictionary representation.

        Returns:
            dict: Dictionary containing all step attributes.
        """
        return {
            "chat_completions": self.chat_completions,
            "observation": self.observation,
            "thought": self.thought,
            "action": self.action,
            "model_response": self.model_response,
            "info": self.info,
            "tool_reward": self.tool_reward,
            "model_reward": self.model_reward,
            "reward": self.reward,
            "done": self.done,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Step":
        """Create a Step instance from a dictionary.

        Args:
            data: Dictionary containing step attributes.

        Returns:
            Step: New Step instance initialized with data from dictionary.
        """
        return cls(
            chat_completions=data.get("chat_completions", []),
            observation=data.get("observation"),
            thought=data.get("thought", ""),
            action=data.get("action"),
            model_response=data.get("model_response", ""),
            info=data.get("info", {}),
            tool_reward=data.get("tool_reward", 0.0),
            model_reward=data.get("model_reward", 0.0),
            reward=data.get("reward", 0.0),
            done=data.get("done", False),
        )


@dataclass
class Trajectory:
    """
    Represents a complete trajectory of agent interactions.

    A trajectory contains multiple steps and tracks the cumulative state and rewards
    throughout an episode. It includes both the conversation history and tokenized
    representations for model training.
    """

    # Unique identifier for this trajectory
    request_id: int = 0
    # ID of parent trajectory (for group-based generation)
    parent_id: int | None = None
    # Current rollout instance ID
    curr_rollout_instance_id: int | None = None
    # Current version tag
    curr_version_tag: int | None = None

    # List of Step objects comprising this trajectory
    steps: list[Step] = field(default_factory=list)
    # Number of assistant (model) turns taken
    assistant_turns: int = 0
    # Number of user (environment) turns taken
    user_turns: int = 0
    # Total reward accumulated for this trajectory
    reward: float | None = None
    # Total length of generated responses in tokens
    response_length: int = 0
    # Additional metadata or debug information
    info: dict = field(default_factory=dict)

    # State variables
    prompt_ids: list[int] = field(default_factory=list)
    response_ids: list[int] = field(default_factory=list)
    response_mask: list[int] = field(default_factory=list)
    response_logprobs: list[float] = field(default_factory=list)


ObsType = TypeVar("ObsType")
ActType = TypeVar("ActType")


class AgentData(ABC, Generic[ObsType, ActType]):
    """
    Abstract base class for managing agent trajectory data during rollout.

    This class handles the state and data flow during agent-environment interactions,
    including trajectory initialization, updates from model/environment, reward computation,
    and preparation of training data. Subclasses should implement specific logic for
    different interaction formats (e.g., tool-based, conversational).

    Type Parameters:
        ObsType: Type of observations received from the environment
        ActType: Type of actions taken by the agent
    """

    _registry: dict[str, type["AgentData"]] = {}
    _class_initialized = False

    def __init__(
        self,
        config: DictConfig,
        reward_manager: ray.actor.ActorHandle,
        tokenizer: AutoTokenizer,
        env: Environment,
        **kwargs,
    ):
        """Initialize the AgentData instance.

        Args:
            config: Configuration object containing training settings
            reward_manager: Ray actor handle for computing rewards
            tokenizer: Tokenizer for converting between text and tokens
            **kwargs: Additional keyword arguments from configuration
        """
        self.init_class(config=config, tokenizer=tokenizer, **kwargs)
        self.config = config
        self.reward_manager = reward_manager
        self.tokenizer = tokenizer
        self.env = env
        self.trajectory = Trajectory()

        # Discount factor for reward discounting (default: 0.0)
        self.gamma = self.config.gen_actor_rollout_ref.rollout.agent.gamma
        # Coefficient for reward shaping (default: 0.0)
        self.reward_bonus_coeff = self.config.gen_actor_rollout_ref.rollout.agent.reward_bonus_coeff

    @classmethod
    def init_class(cls, config: DictConfig, tokenizer: AutoTokenizer, **kwargs):
        """This is used to do heavy initialization work that should shared across all instances. It's only called once.

        Args:
            config (DictConfig): trainer config.
            tokenizer (AutoTokenizer): Tokenizer for tokenize messages.
            **kwargs: extra kwargs from config file passed in by `hydra.utils.instantiate`.
        """
        if cls._class_initialized:
            return
        cls._class_initialized = True

    def start_step(self, observation: ObsType, reward: float | None, done: bool, info: dict | None) -> Step:
        """Start (append) a new step to the trajectory.

        Subclasses are encouraged to call this at the beginning of `update_from_env`
        to avoid relying on the implicit `steps[-1]` contract.

        Args:
            observation: Observation from environment.
            reward: Optional env/tool reward.
            done: Env done flag.
            info: Metadata.

        Returns:
            The newly created Step.
        """
        step = Step(
            # chat_completions must always be ConversationType.
            # Let subclasses decide how to convert observation into ConversationType.
            chat_completions=[],
            observation=observation,
        )
        step.tool_reward = reward
        step.done = done
        step.info = info or {}
        self.trajectory.steps.append(step)
        return step

    @abstractmethod
    def format_chat_completions(self, observation: ObsType, *, is_init: bool) -> ConversationType:
        """Convert an environment observation into ConversationType for Step.chat_completions.

        Design notes:
        - Step.chat_completions is considered a normalized chat history format used by
          downstream tooling / debugging / logging, independent of the raw ObsType.
        - For non-chat environments, subclasses can choose any representation as long
          as it is a list of {"role": str, "content": str} dicts.

        Args:
            observation: Raw observation from environment (ObsType).
            is_init: Whether this is the first observation of the trajectory.

        Returns:
            ConversationType: a list of chat messages.
        """
        raise NotImplementedError

    def get_current_step(self) -> Step:
        """Get the current (latest) step.

        Raises a clearer error than an IndexError if subclasses call into
        step-dependent helpers before starting a step.
        """
        if len(self.trajectory.steps) == 0:
            raise RuntimeError(
                "No step exists in trajectory yet. Ensure `update_from_env()` (or `start_step()`) "
                "is called before `update_from_model_*()` methods."
            )
        return self.trajectory.steps[-1]

    def append_prompt_ids(self, prompt_ids: list[int]) -> None:
        """Set prompt token ids for the trajectory."""
        self.trajectory.prompt_ids = list(prompt_ids)

    def append_user_tokens(self, token_ids: list[int]) -> None:
        """Append tokens that come from the environment/user side.

        These tokens should not be trained on, so response_mask is 0.
        Subclasses may override if they use a different masking scheme.
        """
        if not token_ids:
            return
        self.trajectory.user_turns += 1
        self.trajectory.response_ids += list(token_ids)
        self.trajectory.response_mask += [0] * len(token_ids)
        self.trajectory.response_length += len(token_ids)
        if len(self.trajectory.response_logprobs) > 0:
            # Keep alignment if logprobs are being tracked.
            self.trajectory.response_logprobs += [0.0] * len(token_ids)

    def append_assistant_tokens(self, token_ids: list[int], logprobs: list[float] | None = None) -> None:
        """Append tokens generated by the model/assistant side.

        Args:
            token_ids: Generated token ids.
            logprobs: Optional per-token logprob list aligned to token_ids.
        """
        if not token_ids:
            return
        self.trajectory.assistant_turns += 1
        self.trajectory.response_ids += list(token_ids)
        self.trajectory.response_mask += [1] * len(token_ids)
        self.trajectory.response_length += len(token_ids)
        if logprobs:
            self.trajectory.response_logprobs += list(logprobs)

    def set_step_action(self, action: ActType) -> None:
        """Set parsed action for the current step."""
        self.get_current_step().action = action

    def set_step_model_response(self, text: str) -> None:
        """Set raw model response text for the current step."""
        self.get_current_step().model_response = text

    def add_step_chat_message(self, message: dict[str, Any]) -> None:
        """Append a chat-format message into current step's chat completion list."""
        step = self.get_current_step()
        # Preserve backward compatibility: Step.chat_completions is a list.
        step.chat_completions.append(message)

    @abstractmethod
    def reset(self) -> None:
        """Reset the agent data to initial state.

        This method should clear any accumulated trajectory data and prepare
        the agent for a new episode. Must be implemented by subclasses.
        """
        return

    @abstractmethod
    def encode_observation(self, observation: ObsType, *, is_init: bool) -> tuple[list[int], bool]:
        """Encode an environment observation into token IDs.

        Default implementation indicates "not implemented" so subclasses can
        keep implementing `update_from_env` directly.

        Returns:
            (token_ids, is_prompt):
              - token_ids: token ids derived from observation
              - is_prompt: whether these ids should be treated as prompt_ids
        """
        raise NotImplementedError

    @abstractmethod
    def decode_action_from_token_ids(self, token_ids: list[int]) -> ActType:
        """Decode model-generated token ids into an environment action.

        Default isn't implemented so subclasses can keep implementing
        `update_from_model_token_ids` directly.
        """
        raise NotImplementedError

    def init_trajectory(self, request: Any) -> None:
        """Initialize a new trajectory based on the input request.

        Sets up the trajectory with initial metadata like request_id and parent_id.
        Subclasses should implement this to handle request-specific initialization.

        Args:
            request: Input request containing initial task information.

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError(f"{self.__class__.__name__} must implement init_trajectory method.")

    async def update_from_env(
        self,
        observation: ObsType,
        reward: float | None,
        done: bool,
        info: dict,
        **kwargs,
    ) -> bool:
        """Update agent data from environment feedback.

        This method processes the environment's response after an action is taken,
        updating the trajectory with new observations and rewards.

        Args:
            observation: Observation received from the environment
            reward: Reward value from the environment (if applicable)
            done: Whether the episode has terminated
            info: Additional information from the environment
            **kwargs: Additional keyword arguments

        Returns:
            bool: True if the trajectory should be finalized, False otherwise

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError(f"{self.__class__.__name__} must implement update_from_env method.")

    async def update_from_model_token_ids(self, output: Any, **kwargs) -> tuple[ActType, bool]:
        """Update agent data from model token ids output.

        Processes raw token IDs generated by the model, extracting actions and
        updating the trajectory state accordingly.

        Args:
            output: Model output containing generated token IDs
            **kwargs: Additional keyword arguments

        Returns:
            tuple: (action, done) where action is the extracted action and done
                indicates if the trajectory should be finalized

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError(f"{self.__class__.__name__} must implement update_from_model_token_ids method.")

    async def update_from_model_chat_completion(self, output: Any, **kwargs) -> tuple[ActType, bool]:
        """Update agent data from model chat completion output.

        Processes structured chat completion output from the model, extracting
        actions and updating the trajectory state.

        Args:
            output: Model output in chat completion format
            **kwargs: Additional keyword arguments

        Returns:
            tuple: (action, done) where action is the extracted action and done
                indicates if the trajectory should be finalized

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement update_from_model_chat_completion method."
        )

    def update_trajectory_state_from_output(self, output: DataProto, **kwargs):
        """Update trajectory state based on model output dataproto."""
        self.trajectory.curr_rollout_instance_id = output.non_tensor_batch.get("rollout_instance_id", [None])[0]
        self.trajectory.curr_version_tag = output.non_tensor_batch.get("version_tag", [None])[0]
        self.get_current_step().info["rollout_instance_id"] = output.non_tensor_batch.get(
            "rollout_instance_id", [None]
        )[0]

    def prepare_generation_request(self, request: DataProto) -> DataProto:
        """Prepare the generation request based on the current agent data state.

        Args:
            request (DataProto): Original input request.

        Returns:
            DataProto: Modified request for generation.
        """
        assert len(request) == 1, "prepare_generation_request only supports single request."
        assert "input_ids" in request.batch, "Request must contain 'input_ids' in batch."

        request.non_tensor_batch["raw_prompt_ids"] = np.array(
            [self.trajectory.prompt_ids + self.trajectory.response_ids]
        )
        if self.trajectory.curr_rollout_instance_id is not None:
            request.non_tensor_batch["rollout_instance_id"] = np.array([self.trajectory.curr_rollout_instance_id])
        if self.trajectory.curr_version_tag is not None:
            request.non_tensor_batch["version_tag"] = np.array([self.trajectory.curr_version_tag])

        return request

    def compute_step_reward(self, step: Step) -> float:
        """
        Compute the step-level reward.
        Default: sum of tool_reward and model_reward

        Args:
            step: The step to compute the reward for.
        Returns:
            The computed step reward.
        """
        tool_reward = step.tool_reward if step.tool_reward is not None else 0.0
        model_reward = step.model_reward if step.model_reward is not None else 0.0
        step.reward = tool_reward + model_reward
        return step.reward

    def adjust_step_rewards(self, trajectory: Trajectory) -> None:
        """
        Adjust the step-level rewards using reward shaping and discounting.

        Applies two optional transformations:
        1. Reward shaping: Adds bonus based on reward differences between steps
        2. Monte Carlo returns: Computes discounted cumulative rewards

        Both transformations are disabled by default (coefficients = 0.0).

        Args:
            trajectory: The trajectory to adjust the rewards for.
        """
        # Reward shaping: add bonus proportional to reward deltas
        # Formula: s[i].reward = s[i].reward + bonus * (s[i].reward - s[i-1].reward) for i > 0
        if self.reward_bonus_coeff > 0.0:
            raw_rewards = [step.reward for step in trajectory.steps]
            for i in range(1, len(trajectory.steps)):
                trajectory.steps[i].reward += self.reward_bonus_coeff * (raw_rewards[i] - raw_rewards[i - 1])

        # Compute Monte Carlo returns (backward iteration)
        # Formula: G_t = R_{t+1} + γ * R_{t+2} + γ² * R_{t+3} + ... + γ^{T-t-1} * R_T
        if self.gamma > 0.0:
            G = 0.0
            for step in reversed(trajectory.steps):
                G = step.reward + self.gamma * G
                step.reward = G  # Replace the reward with MC return

    async def finalize_output(self, request: DataProto) -> DataProto:
        """Finalize the trajectory and prepare output for training.

        This method truncates sequences to the maximum response length, computes
        final rewards, and packages the trajectory data into a format suitable
        for training.

        Args:
            request: Original request DataProto containing metadata.

        Returns:
            DataProto: Finalized output with rewards and trajectory information.
        """
        self.trajectory.response_ids = self.trajectory.response_ids[
            : self.config.gen_actor_rollout_ref.rollout.response_length
        ]
        self.trajectory.response_mask = self.trajectory.response_mask[
            : self.config.gen_actor_rollout_ref.rollout.response_length
        ]
        self.trajectory.response_logprobs = self.trajectory.response_logprobs[
            : self.config.gen_actor_rollout_ref.rollout.response_length
        ]

        non_tensor_batch = request.non_tensor_batch
        non_tensor_batch["raw_prompt_ids"] = np.array([self.trajectory.prompt_ids])
        non_tensor_batch["raw_response_ids"] = np.array([self.trajectory.response_ids])
        non_tensor_batch["response_mask"] = np.array([self.trajectory.response_mask])
        non_tensor_batch["rollout_instance_id"] = np.array([self.trajectory.curr_rollout_instance_id])
        non_tensor_batch["__num_turns__"] = np.array(
            [self.trajectory.assistant_turns + self.trajectory.user_turns + 1], dtype=np.int32
        )
        if len(self.trajectory.response_logprobs) > 0:
            non_tensor_batch["rollout_log_probs"] = np.array([self.trajectory.response_logprobs])

        data = DataProto(non_tensor_batch=non_tensor_batch, meta_info=request.meta_info)

        output: DataProto = data

        if self.config.gen_actor_rollout_ref.rollout.agent.traj_reward_mode == "step":
            assert not self.config.reward_model.launch_reward_fn_async, (
                "Asynchronous reward computation is not supported in 'step' traj_reward_mode."
            )
            self.trajectory.reward = np.sum([self.compute_step_reward(step) for step in self.trajectory.steps])
            if len(self.trajectory.steps) > 1:
                self.adjust_step_rewards(self.trajectory)
            reward_result = {non_tensor_batch["uid"][0]: {"reward_score": self.trajectory.reward}}
            output = self._post_process_and_merge_reward(reward_result, data)
        elif self.config.gen_actor_rollout_ref.rollout.agent.traj_reward_mode == "traj":
            reward_result = await self.reward_manager.compute_score.remote(data)
            if not self.config.reward_model.launch_reward_fn_async:
                output = self._post_process_and_merge_reward(reward_result, data)
        else:
            raise ValueError(
                f"Unknown traj_reward_mode: {self.config.gen_actor_rollout_ref.rollout.agent.traj_reward_mode}"
            )

        return output

    def _post_process_and_merge_reward(self, reward_result: dict[int, dict], outputs: DataProto) -> DataProto:
        """Merge the computed reward results back into the output DataProto.

        This method updates the output data with the reward scores and any additional
        information returned by the reward model.

        Args:
            reward_result (Dict[int, dict]): Computed reward results indexed by data item.
            outputs (DataProto): Original output data to be updated.

        Returns:
            DataProto: Updated output data with reward information.
        """
        if outputs.meta_info.get("validate", False):
            return outputs  # Skip merging for validation data

        filtered_request_ids = list(reward_result.keys())
        filtered_request_idxs = [
            idx for idx, uid in enumerate(outputs.non_tensor_batch["uid"].tolist()) if uid in filtered_request_ids
        ]
        outputs = outputs.select_idxs(filtered_request_idxs)
        request_ids = outputs.non_tensor_batch["uid"].tolist()

        rewards = []
        reward_extra_infos = []
        for request_id in request_ids:
            assert request_id in reward_result, f"Missing reward result for request ID: {request_id}"
            result = reward_result[request_id]
            rewards.append(result["reward_score"])
            extra_info = result.get("reward_extra_info", {})
            reward_extra_infos.append(extra_info)
        outputs.non_tensor_batch["reward_scores"] = np.array(rewards)
        outputs.non_tensor_batch["reward_extra_infos"] = np.array(reward_extra_infos, dtype=object)
        return outputs

    @classmethod
    def get_agent_data(cls, name: str, *args, **kwargs) -> "AgentData":
        """
        Get an agent data instance by name from the registry.

        Args:
            name: The name of the agent data to retrieve
            *args: Positional arguments to pass to the agent data constructor
            **kwargs: Keyword arguments to pass to the agent data constructor

        Returns:
            AgentData: An instance of the requested agent data

        Raises:
            ValueError: If the agent data is not found in the registry
        """
        if name not in cls._registry:
            raise ValueError(f"Unknown agent data: {name}")
        return cls._registry[name](*args, **kwargs)

    @classmethod
    def register(cls, name: str):
        """
        Decorator to register an agent data class with the registry.

        Args:
            name: The name to register the agent data under

        Returns:
            The decorator function

        Example:
            @AgentData.register("tool_agent_data")
            class ToolAgentData(AgentData):
                def reset(self):
                    # implementation
                    pass
        """

        def decorator(subclass: type["AgentData"]) -> type["AgentData"]:
            cls._registry[name] = subclass
            return subclass

        return decorator
