defaults:
  - megatron_reward_model
  - _self_

use_reward_loop: True
reward_manager: gen
gen_reward_function: default
enable: False
micro_batch_size_per_gpu: 1

# Whether to deploy the model to a separate resource pool.
enable_resource_pool: False
n_gpus_per_node: 2
num_replicas: 2
nnodes: 1
rollout_ngpus_per_instance_per_node: 1
rollout_nnodes_per_instance: 1

model:
  path: ~/models/FsfairX-LLaMA3-RM-v0.1
  external_lib: ${oc.select:train_actor_rollout_ref.model.external_lib,null}
  trust_remote_code: False

rollout:
  _target_: psrl.workers.config.RolloutConfig
  runner: pooling
  task: classify
  name: vllm
  dtype: bfloat16
  gpu_memory_utilization: 0.5
  enforce_eager: true
  cudagraph_capture_sizes: null
  free_cache_engine: true
  data_parallel_size: 1
  expert_parallel_size: 1
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  max_num_batched_tokens: 8192
  max_model_len: null
  max_num_seqs: 1024
  load_format: auto
  engine_kwargs: {}
  limit_images: null
  enable_chunked_prefill: false
  enable_prefix_caching: false
  disable_log_stats: true
  skip_tokenizer_init: false

  prompt_length: 2048
  response_length: 2048

  pooling_config:
    task: classify
    use_activation: false
    normalize: false