# configs for the reward model
launch_reward_fn_async: True

reward_normalization: group

reward_models:
  - reward_loop_type: naive
    reward_fn: 
      - default

  - reward_loop_type: dapo
    reward_fn: 
      - default
    reward_loop_kwargs:
      max_resp_len: 5120
      overlong_buffer_cfg:
        enable: True
        len: 3072
        penalty_factor: 1.0
        log: False

  # - reward_loop_type: gen
  #   reward_fn: 
  #     - default
  #   model_name: Qwen3-8B

  #   enable_resource_pool: True
  #   n_gpus_per_node: 1
  #   num_replicas: 1
  #   nnodes: 1
  #   rollout_ngpus_per_instance_per_node: 1
  #   rollout_nnodes_per_instance: 1

  #   model:
  #     path: /jizhicfs/pkuhetu/models/Qwen3-8B
  #     external_lib: ${oc.select:train_actor_rollout_ref.model.external_lib,null}
  #     trust_remote_code: False

  #   rollout:
  #     _target_: psrl.workers.config.RolloutConfig
  #     name: vllm
  #     mode: psrl_async
  #     disable_attn: False
  #     dtype: bfloat16
  #     gpu_memory_utilization: 0.5
  #     enforce_eager: true
  #     cudagraph_capture_sizes: null
  #     free_cache_engine: true
  #     data_parallel_size: 1
  #     expert_parallel_size: 1
  #     tensor_model_parallel_size: 1
  #     pipeline_model_parallel_size: 1
  #     max_num_batched_tokens: 8192
  #     max_num_seqs: 1024
  #     load_format: auto
  #     engine_kwargs: {}
  #     limit_images: null
  #     enable_chunked_prefill: false
  #     enable_prefix_caching: false
  #     disable_log_stats: true
  #     skip_tokenizer_init: false

  #     prompt_length: 4096
  #     response_length: 4096
  #     max_model_len: 8192

  #     runner: generate
  #     task: generate

  #   sampling_config:
  #     temperature: 0.0
  #     top_p: 1.0
  #     top_k: 0
  
  - reward_loop_type: gen
    reward_fn: 
      - skywork
    reward_model_name: Skywork-Reward-V2-Qwen3-8B

    enable_resource_pool: True
    n_gpus_per_node: 1
    num_replicas: 1
    nnodes: 1
    rollout_ngpus_per_instance_per_node: 1
    rollout_nnodes_per_instance: 1

    model:
      path: /jizhicfs/pkuhetu/yfzhao/psrl/models/Skywork-Reward-V2-Qwen3-8B
      external_lib: ${oc.select:train_actor_rollout_ref.model.external_lib,null}
      trust_remote_code: False

    rollout:
      _target_: psrl.workers.config.RolloutConfig
      name: vllm
      mode: psrl_async
      disable_attn: False
      dtype: bfloat16
      gpu_memory_utilization: 0.5
      enforce_eager: true
      cudagraph_capture_sizes: null
      free_cache_engine: true
      data_parallel_size: 1
      expert_parallel_size: 1
      tensor_model_parallel_size: 1
      pipeline_model_parallel_size: 1
      max_num_batched_tokens: 20480
      max_num_seqs: 1024
      load_format: auto
      engine_kwargs: {}
      limit_images: null
      enable_chunked_prefill: false
      enable_prefix_caching: false
      disable_log_stats: true
      skip_tokenizer_init: false

      prompt_length: 8192
      response_length: 8192
      max_model_len: 16384

      runner: pooling
      task: classify

    pooling_config:
      task: classify
      use_activation: false
      normalize: false

  # - reward_loop_type: naive
  #   reward_fn: 
  #     - None
  #   # Cloud/local sandbox fusion configuration for custom reward logic
  #   sandbox_fusion:
  #     # Cloud /local function URL for sandbox execution
  #     url: null
  #     # Max concurrent requests allowed to sandbox
  #     max_concurrent: 64
  #     # Max memory limit for each sandbox process in MB
  #     memory_limit_mb: 1024


# profile the reward model in `compute_reward` 
profiler:
  # Required when using verl.utils.omega_conf_to_dataclass to instantiate dataclass configs
  _target_: verl.utils.profiler.ProfilerConfig
  # profiler tool, default same as profiler.tool in global config
  # choices: nsys, npu, torch
  tool: ${oc.select:global_profiler.tool,null}
  # whether enable profile on ref
  enable: False
  # Whether to profile all ranks.
  all_ranks: False
  # The ranks that will be profiled. [] or [0,1,...]
  ranks: []
  # profile results saving path
  save_path: ${oc.select:global_profiler.save_path,null}
  # specific tool config
  tool_config: ${oc.select:train_actor_rollout_ref.actor.profiler.tool_config,null}
