# defaults specify the default config from each component
defaults:

  # fsdp optimizer config
  - ../optim@optim: fsdp

  # fsdp engine config
  - ../engine@fsdp_config: fsdp

  # dp actor config, inheriting from trainer/config/actor/actor.yaml
  - actor

  # load the reference default config, then apply the fields in the current yaml
  - _self_

# Target class for this configuration
_target_: pivotrl.workers.config.FSDPActorConfig

strategy: fsdp2

# Gradient clipping for actor updates, specific to the strategy.
grad_clip: 1.0

# Sequence parallelism size for Ulysses-style model parallelism
# oc.select: the default val for ref.ulysses_sequence_parallel_size
ulysses_sequence_parallel_size: 1

# calculate entropy with chunking to reduce memory peak
entropy_from_logits_with_chunking: False

# recompute entropy
entropy_checkpointing: False

# Whether to remove padding tokens in inputs during training
use_remove_padding: ${oc.select:train_actor_rollout_ref.model.use_remove_padding,false}
