# Whether colocate rollout and trian workers
colocate: False

# IP address of parameter server managaer.
ps_manager_ip: 127.0.0.1

# IP address of reward service.
reward_service_ip: ${psrl.ps_manager_ip}

# Staleness control of training data.
staleness: 0

# Size of each staleness buffer (i.e. training batch)
staleness_buffer_entries: 512

# number of responses (i.e. num sample times). > 1 for grpo
rollout_n: 1

# Generate mode: batch or stream
gen_mode: batch

# Weight synchronization mode for parameter server: cpu_ref or nixl_cpu
ps_mode: cpu_ref

# Logging path
logging_path: ~/psrl_logs

# Config for profile
profile:

  # Whether to disable the attention in Qwen2.5
  disable_attn: False

  # Whether to fix the weight of the model
  # Useful for analysis
  fix_weight: False

# Config for logprobs
log_prob:

  # Whether to return logprobs from rollout engines
  enable_rollout_engine_log_prob: True

# Worker deployment and resource allocation
deployment:

  # Number for rollout instances
  n_rollout_instances: 1

  # Node number for each rollout instance
  rollout_nnodes_per_instance: 1

  # GPU number for each rollout instance in every node
  rollout_ngpus_per_node_per_instance: 1

  # Node number for trainer
  train_nnodes: 1

  # GPU number for trainer in every node
  train_ngpus_per_node: 1
  
  # Rollout with heterogeneous strategies across different instances
  heterogeneous_rollout:

    # Whether to enable heterogeneous strategies for different rollout instances.
    enable: False

    # Number for rollout instances
    n_rollout_instances: ${psrl.deployment.n_rollout_instances}

    # Node number for each rollout instance
    rollout_nnodes_per_instance: []

    # GPU number for each rollout instance in every node
    rollout_ngpus_per_node_per_instance: []

    # Tensor model parallel size for each rollout instance.
    tensor_model_parallel_size_per_instance: []

    # Pipeline model parallel size for each rollout instance.
    pipeline_model_parallel_size_per_instance: []

# Collect rollout instance status to rollout coordinator for global dp load balance
status_collection:

  # whether to enable the status collection.
  enable: True

  # The level of logging to file
  # Available options: "none", "partial_rollout", "prompt", "generation", "all"
  dump_logging_to_file_level: generation

  # Logging interval in milliseconds
  dump_logging_to_file_interval_in_ms: 2000

  # Engine status sync interval in millisecond (each vllm engine -> rollout coordinator)
  # Here 10 means sync every 0.01 second
  engine_sync_interval_in_ms: 10

  # Coordinator sync interval in millisecond (rollout coordinator after collecting engine status from all vllm engines -> router)
  # Here 10 means sync every 0.01 second
  coordinator_sync_interval_in_ms: 10

# Redundant rollout config
redundant_rollout:

  # Whether to enable redundant rollout
  enable: False

  # Global batch size for algorithm requirement
  alg_global_batch_size: ${psrl.staleness_buffer_entries}

  # Number of responses for algorithm requirement
  alg_rollout_n: ${psrl.rollout_n}

  # Actual global batch size (>= algorithm requirement)
  redundant_global_batch_size: null

  # Actual number of responses (>= algorithm requirement)
  redundant_rollout_n: null

# Partial rollout config
partial_rollout:

  # Whether to enbale partial rollout
  enable: False

  # Whether view interrupted trajectories as new prompts
  interrupt_as_prompt: False

# Rollout routing strategy config
routing_strategy:

  # Method for rollout routing
  # Available options: "random", "round_robin", "request_num_balance", "throughput_optimal", "throughput_optimal_with_budget"
  # If using "request_num_balance" or "throughput_optimal" or "throughput_optimal_with_budget", you need to enable status collection.
  method: request_num_balance

  # Check interval in millisecond for rollout routing
  check_interval_in_ms: 1000

  # Whether to prioritize short requests
  short_request_first: False

  # Whether to sort the candidates by indicator 
  sort_candidate_by_indicator: False

  # Whether to allocate the version tag dynamically (first routing to the instance, then allocate the version tag)
  enable_dynamic_version_tag: False

  # Whether to enable multiple priority queues for routing requests
  enable_multi_priority_queue: False

  # Whether to enable group sampling on multiple instances
  enable_group_sampling_on_multi_instances: True

  # Logging interval in milliseconds
  logging_interval_in_ms: 2000

  # Path to the cost model (a json file)
  cost_model_path: null

  # Delta throughput threshold to stop request routing to an instance
  delta_throughput_threshold: 0.5

  # Request budget in tokens for each request
  # It is used to estimate the length of the response tokens
  request_budget: 1024

  # Snapshot staleness threshold in milliseconds
  # Here snapshot_staleness_threshold_ms is the time difference between the last time record and the snapshot time of the engine status.
  snapshot_staleness_threshold_in_ms: 1000

  # Max number of waiting requests per instance after preemption
  max_num_waiting_reqs_after_preemption: 1000

  # Max estimated concurrent sequences per instance
  # No need to tune this value, it is only used to estimate the max sequence length that can saturate the KV Cache
  max_estimated_concurrent_seqs_per_instance: 32768

  # The actual max number of concurrent sequences per instance
  max_concurrent_seqs_per_instance: 1024

# Model synchronization and rollout migration strategy config
sync_and_mig_strategy:

  # Method for model synchronization and rollout migration
  # Available options: "status_based" or "greedy"
  method: status_based

  # Check interval in millisecond for model synchronization and rollout migration
  check_interval_in_ms: 100

  # Model synchronization config
  sync:
    # Indicator for model synchronization
    # Available options: "request_num", "throughput", "kv_cache", "hypothesis_test"
    # request_num: we check if the number of requests is lower than the threshold
    # throughput: we check if the throughput is lower than the threshold
    # kv_cache: we check if the KV Cache is saturated
    # hypothesis_test (TODO): we check if there are any benefits from synchronization
    indicator: request_num
  
    # Workload threshold to trigger model synchronization
    # When indicator is "request_num", threshold is the number of requests.
    # When indicator is "throughput", threshold is the throughput.
    # When indicator is "kv_cache", threshold is the KV Cache utilization.
    # When indicator is "hypothesis_test", threshold is not used.
    threshold: null

  # Rollout migration config
  mig:
    # Whether to enable rollout migration
    enable: False

    # Indicator for rollout migration
    # Available options: "request_num", "throughput", "kv_cache"
    indicator: request_num

    # Relative threshold for rollout migration
    # When the indicator of the instance with the max indicator value divided by the indicator of the instance with the min indicator value is greater than the threshold, 
    # the rollout coordinator will abort all rollout requests of the instance with the max indicator value (the requests will loop back to the router).
    threshold: null

    # Stop migration when the indicator is less than the threshold
    # Available options: "request_num", "throughput", "kv_cache"
    stop_indicator: request_num

    # Threshold for stopping migration
    stop_threshold: null

# NIXL config for `nixl_cpu` weight synchronization
nixl:

  # Parameter server mode: storage_server or meta_server
  server_mode: meta_server

  # Server IP address
  server_ip: ${psrl.ps_manager_ip}

  # Server port
  server_port: 23456

  # Pinned temp memory slots num for non-contiguous transfer
  max_pinned_temp_memory_slots: 8

# Post processor for group requests in streaming mode
group_post_process:

  # Whether to enable group post-processing
  enable: False

  # Name of the registered group post-processor to use
  # Available options: "dynamic_sampling_filter", "no_filter"
  # When name is "dynamic_sampling_filter", requires algorithm.filter_groups.metric to be set
  name: null

# Post processor for buffer requests in batch mode
buffer_post_process:

  # Whether to enable buffer post-processing
  enable: False

  # Name of the registered buffer post-processor to use
  # Available options: "dynamic_sampling_filter", "no_filter"
  # When name is "dynamic_sampling_filter", requires algorithm.filter_groups.metric to be set
  name: null

# Buffer bound for retry mechanism
retry_bound: -1

# Ratio over retry bound
retry_ratio: 1.0